[project]
name = "mycrew"
version = "0.1.0"
description = "mycrew using crewAI"
authors = [{ name = "Fabrice Fourel", email = "ffourel@gmail.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.4.1",
    "fastapi[standard]>=0.121.1",
]



[tool.crewai]
type = "crew"
